spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${HOME}/eclipse-workspace/spring-config-server-test-properties.git
          searchPaths: "{application}"